version: "3.9"

services:
  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./models:/root/.ollama/models  # Store models in local folder
      - ollama-data:/root/.ollama      # Keep other Ollama data
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - lentera

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Lentera ChatAI
      - WEBUI_URL=http://0.0.0.0:8080
      - WEBUI_SECRET_KEY=secret
    restart: unless-stopped
    networks:
      - lentera

volumes:
  ollama-data:
  open-webui-data:

networks:
  lentera:
